### PR TITLE
Support the web

### PR DESCRIPTION
**Pull request by jasonLaster**
This PR adds support for requiring chrome-remote-interface in a web context.

**The API remains the same**

```js
const CDP = CDP("chrome-remote-interface");
CDP.List().then(tabs => console.log);
```

**What's added**

* webpack builds a bundle during `prepublish` 
* webpack wraps `ws` 
* webpack replaces `externalRequest` with a module that calls `window.externalRequest`

**What did I change in your patch:**

* I tried to be more webpack friendly and remove the step of building the library and including a script tag
* I dropped webpack.entry in favor of using index.js as the entry
* I added the package.json "browser" field so that webpack could find the file

Here's my PR which uses this branch successfully https://github.com/devtools-html/debugger.html/pull/1320

Changes:
* dropped [CDP](https://github.com/jasonLaster/chrome-remote-debugging-protocol). I encourage you to check out the library. Especially:
  * how we prebuild the api
  * how the inspector backend has a cool type layer
* i switched our event handler and commands to use the object signature and promise wrapper
* not much else. Your library is pretty great and i'm excited to start working on top of it.

### CODE REVIEW

**Comment by cyrus-and** [comment]
This is great news! :)

I have some questions/requests/comments:

- I'm not super happy to include the output .js into the NPM mode, but there is no easy way around I guess...

- Suppose a user doesn't want to use webpack, how can he manage to obtain a valid .js to use directly with a `<script>` tag?

- I'd like to keep the fact that the `criRequest` function accepts two arguments only. It would be great if you could rebase this onto the tip of `webpack` branch (b046e46155508778f19f1cbccabeb38f411815aa). Also, using a real function and let the runtime to produce the string is IMO nicer.

- Finally, if you could add a more descriptive title and message (this PR message will surely do).

**Comment by jasonLaster** [comment]
> I'm not super happy to include the output.js into the NPM mode

Yeah, my test is *does* this require committing a bundle per version bump and thankfully it does not. By the way, I didn't know this, but you can test `npm publish` by running `npm pack` and see the tar ball npm creates.


> Suppose a user doesn't want to use webpack, how can he manage to obtain a valid .js to use directly with a <script> tag?

I'll add some docs that are similar to what you had before.

> 'd like to keep the fact that the criRequest function accepts two arguments only

👍 

> Finally, if you could add a more descriptive title and message

commit title, message?

**Comment by cyrus-and** [comment]
> commit title, message?

Yeah, sorry, typo.

**Comment by cyrus-and** [comment]
Ahem, sorry but what I meant was to commit this PR changes on top of my [`webpack`][1] branch. I did't wanted to lose that 2 commits that are already there.

[1]: https://github.com/cyrus-and/chrome-remote-interface/tree/webpack

**Comment by jasonLaster** [comment]
:) I thought it was cleaner to have one. 

I think I can roll it back.

**Comment by jasonLaster** [comment]
yup, `git reflog` FTW

**Comment by cyrus-and** [comment]
That's awesome, thanks!
I made some small tweaks which I'm going to push soon; no breaking changes.

But I'm having problems when I try to generate the bundle with `libraryTarget: 'var'`. The `./lib/websocket-wrapper` external becomes:

```js
module.exports = ./lib/websocket-wrapper;
```
Which is clearly an error, see [this table][1]. Any ideas on how to make it work in this scenario too? It's mostly a bonus point but it would be nice tho have also this option.

[1]: https://webpack.github.io/docs/configuration.html#externals

**Comment by jasonLaster** [comment]
> var

Hmm, I believe it worked with your patch. I'd, try slowly adding my patch in and see where it breaks. Sorry I don't have a better idea. Also thanks for testing, I hadn't tried since your patch.

**Comment by cyrus-and** [comment]
Yes but I used `'window.ws'` instead of `'./lib/websocket-wrapper'`. Why does it happen is clear, I'm searching for a workaround. If I can't came up with nice solution, I'll simply drop the *vanilla* JavaScript option for now.

**Comment by jasonLaster** [comment]
Got it.

I suppose it's okay to bring back webpack.entry.

**Comment by cyrus-and** [comment]
Well, TIL [`resolve.alias`][1]... it seems perfect for this use case. I'm pushing everything on the `webpack` branch. Once you can confirm that everything is working fine I will merge into master and bump a new release.

[1]: https://webpack.github.io/docs/configuration.html#resolve-alias

**Comment by jasonLaster** [comment]
Thanks, I like your improvements! Especially the readme cleanup and alias.

I noticed a small bug with the way externalRequest was externalized.

Also, I moved the uglify logic to an optional plugin as webpack and other build tools can do that in the pipeline. The real benefit is a developer workflow thing. When I am working on the Debugger locally the minified source makes it *much* harder to debug CRI. You might guess this about me, but I'm a big debugger user :)

**Comment by cyrus-and** [comment]
Sounds good to me! :)
So can I merge this? Have you performed a bit of testing with your scenario?

Let me fix the failing Travis CI test, then I'm good to go.

**Comment by cyrus-and** [comment]
One thing I've just noticed, while I'm ok with optional compression I believe that it should be turned on by default, I don't want to burden the NPM bundle with non-minified replicated code (577 kB vs 293 kB).

**Comment by jasonLaster** [comment]
That works for me.

Excited this is landing.

**Comment by cyrus-and** [comment]
Landed and published ([v0.17.0][1]), we finally made it! :)

[1]: https://github.com/cyrus-and/chrome-remote-interface/releases/tag/v0.17.0

**Pull request merged**
