### PR TITLE
bump ws to 7.2.0

### PR DESCRIPTION
**Pull request by nehashri**

### CODE REVIEW

**Comment by cyrus-and** [comment]
Is there a particular reason?

**Comment by nehashri** [comment]
the version [7.0.0](https://github.com/websockets/ws/releases/tag/7.0.0) of ws has some fixes that I am facing in my setup right now. The error I am facing for readyState is the same as mentioned in their release notes. 
Also, they seem to have dropped support for node 6.

**Comment by cyrus-and** [comment]
Alright, thanks for the clarification.

**Comment by nehashri** [comment]
When can we expect a new release with this updated dependency?

**Comment by cyrus-and** [comment]
Right now: [0.28.1](https://www.npmjs.com/package/chrome-remote-interface/v/0.28.1).

**Comment by nehashri** [comment]
Thanks

**Pull request merged**
