### PR TITLE
Add close and spawn tab methods

### PR DESCRIPTION
**Pull request by gcochard**
The devtools HTTP server has an undocumented feature that will let you spawn and close tabs. This PR implements those features and adds tests for them.

### CODE REVIEW

**Comment by cyrus-and** [comment]
Good find!
Are these features discussed somewhere? Even a link to the devtools repository would do...

Give me a couple of days to review it (can't work on it right now). In the meanwhile, if you feel like, you can fix the documentation of these two new methods as it still reports:

> Request the list of the available open tabs of the remote Chrome instance.

Thanks!

**Comment by gcochard** [comment]
Here's the source: https://src.chromium.org/viewvc/chrome/trunk/src/content/browser/devtools/devtools_http_handler_impl.cc
Starts at line 492. From what I can see, the API has been stable for a while now. [Here is a code review](https://codereview.chromium.org/39993002/diff/370001/content/browser/devtools/devtools_http_handler_impl.cc) for the last time it was modified, and a [code review for when it was added](https://chromiumcodereview.appspot.com/11033046).

I'll add support for the URL query parameter in `/json/new` as well as fixing the documentation.

**Comment by gcochard** [comment]
@cyrus-and All good, review at will.

**Comment by cyrus-and** [comment]
I changed a couple of things, I tried to explain the reason in the commit messages.

I also added you to the collaborators but without email (since I cannot find it :)), if you wish complete/change/delete your personal information please let me know.

**Pull request merged**
