### PR TITLE
Update dependencies.

### LINKED ISSUE #296: DoS Vulnerability in dependency - ws
https://snyk.io/test/npm/chrome-remote-interface/0.25.2?severity=high&severity=medium&severity=low

Fixed in [ws@3.3.1](https://github.com/websockets/ws/releases/tag/3.3.1).

### PR DESCRIPTION
**Pull request by westy92**
Fixes #296.

### CODE REVIEW

**Comment by westy92** [comment]
Should I update devDependencies as well?

**Comment by cyrus-and** [comment]
About #296, no WebSocket server is used here, but whatever...

> Should I update devDependencies as well?

Is there a compelling reason?

**Comment by westy92** [comment]
It's a good idea to keep dependencies up-to-date, mostly due to bugfixes.

**Comment by cyrus-and** [comment]
I kind of disagree, more than once this policy led me to deal with unexpected bugs. I prefer to wait for a bug to surface in the main repo in order to update a dependency.

I'm going to merge this PR.

**Pull request merged**
