### PR TITLE
Make rejections instance of Error

### PR DESCRIPTION
**Pull request by Janpot**
fixes https://github.com/cyrus-and/chrome-remote-interface/issues/70

### CODE REVIEW

**Comment by cyrus-and** [comment]
Thanks! I'd like to keep that error *opaque* though... I know that it might be useful to check if `error instanceof Chrome.ProtocolError` but I don't like to pollute that namespace with something that is not a DevTools method for now (related #60).

If you could squash these commits by removing the export it would be great.

**Comment by Janpot** [comment]
@cyrus-and export removed and commits squashed

**Comment by cyrus-and** [comment]
Great, thank you!

> FYI, in github you can now 'rebase and squash' instead of merging a PR

Yeah, but I don't know whether it preserves the author or not. (Does it?) I didn't want to erase your contribution. I usually do everything from the command line.

**Comment by Janpot** [comment]
I'm not 100% sure but I think it preserves me as author and adds you as committer.

**Comment by cyrus-and** [comment]
Cool, gotta try next time.

**Pull request merged**
