### PR TITLE
Add instructions for augmented TypeScript typings

### PR DESCRIPTION
**Pull request by kazarmy**
This pr adds instructions in README.md on installing augmented TypeScript typings for the statements in #500, as well as making some corrections.

### CODE REVIEW

**Comment by kazarmy** [comment]
@slhck @westy92

**Review by westy92 — APPROVED** [review]

**Comment by slhck** [comment]
LGTM

**Comment by cyrus-and** [comment]
Out of curiosity, what's with `0.0.927104` in `devtools-protocol@0.0.927104`?

**Comment by slhck** [comment]
> Out of curiosity, what's with `0.0.927104` in `devtools-protocol@0.0.927104`?

That's the tag of the respective npm package: https://github.com/ChromeDevTools/devtools-protocol/tags

Since the types in the referenced repo are not created automatically, they are based on a specific revision of the original types.

**Pull request merged**
